# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/profiles/qemu-guest.nix")
    ];

  boot.initrd.availableKernelModules = [ "ata_piix" "virtio_pci" "uhci_hcd" "ehci_pci" "sr_mod" "virtio_blk" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/fe354ae3-c79e-4dcf-bd4c-c00854479332";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/A7E5-297F";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  fileSystems."/storage/disks/one" =
    { device = "/dev/disk/by-uuid/bf197aab-66d5-4248-a754-470ce872a172";
      fsType = "xfs";
    };

  fileSystems."/storage/disks/two" =
    { device = "/dev/disk/by-uuid/84e599ab-bf44-4b34-9d6b-9defdbc0214f";
      fsType = "xfs";
    };

  fileSystems."/storage/disks/three" =
    { device = "/dev/disk/by-uuid/0a5e23b0-f209-4227-a79d-8a7c01cce9d8";
      fsType = "xfs";
    };

  fileSystems."/storage/disks/four" =
    { device = "/dev/disk/by-uuid/8e7171c6-0e8d-4d71-8e93-5023df6db228";
      fsType = "xfs";
    };

  fileSystems."/storage/cache/data" =
    { device = "/dev/disk/by-uuid/c652b005-395a-4195-b069-6157623789a9";
      fsType = "xfs";
    };

  fileSystems."/storage/cache/appdata" =
    { device = "/dev/disk/by-uuid/df9a2f8d-9eb6-49c4-becd-39672885dffe";
      fsType = "xfs";
    };

  swapDevices = [ ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.ens2.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
}
