# Auto-generated using compose2nix v0.2.3-pre.
{ pkgs, lib, ... }:

{
  # Runtime
  virtualisation.podman = {
    enable = true;
    autoPrune.enable = true;
    dockerCompat = true;
    defaultNetwork.settings = {
      # Required for container networking to be able to use names.
      dns_enabled = true;
    };
  };
  virtualisation.oci-containers.backend = "podman";

  # Containers
  virtualisation.oci-containers.containers."komodo-komodo-core" = {
    image = "ghcr.io/mbecker20/komodo:latest";
    environment = {
      "KOMODO_ENSURE_SERVER" = "http://komodo-periphery:8120";
      "KOMODO_HOST" = "https://komodo.crate.dev";
      "KOMODO_JWT_SECRET" = "a_random_jwt_secret";
      "KOMODO_LOCAL_AUTH" = "true";
      "KOMODO_MONGO_ADDRESS" = "komodo-mongo:27017";
      "KOMODO_MONGO_PASSWORD" = "admin";
      "KOMODO_MONGO_USERNAME" = "admin";
      "KOMODO_PASSKEY" = "zz0notsosafe";
      "KOMODO_TITLE" = "Komodo";
      "KOMODO_WEBHOOK_SECRET" = "zz0notsosafe1";
    };
    ports = [
      "9120:9120/tcp"
    ];
    dependsOn = [
      "komodo-komodo-mongo"
    ];
#    log-driver = "local";
    extraOptions = [
      "--network-alias=komodo-core"
      "--network=komodo_komodo-network"
    ];
  };
  systemd.services."podman-komodo-komodo-core" = {
    serviceConfig = {
      Restart = lib.mkOverride 500 "always";
    };
    after = [
      "podman-network-komodo_komodo-network.service"
    ];
    requires = [
      "podman-network-komodo_komodo-network.service"
    ];
    partOf = [
      "podman-compose-komodo-root.target"
    ];
    wantedBy = [
      "podman-compose-komodo-root.target"
    ];
  };
  virtualisation.oci-containers.containers."komodo-komodo-mongo" = {
    image = "mongo";
    environment = {
      "MONGO_INITDB_ROOT_PASSWORD" = "admin";
      "MONGO_INITDB_ROOT_USERNAME" = "admin";
    };
    volumes = [
      "/cache/appdata/komodo/db-config:/data/configdb:rw"
      "/cache/appdata/komodo/db-data:/data/db:rw"
    ];
    ports = [
      "27017:27017/tcp"
    ];
    cmd = [ "--quiet" ];
#    log-driver = "local";
    extraOptions = [
      "--network-alias=komodo-mongo"
      "--network=komodo_komodo-network"
    ];
  };
  systemd.services."podman-komodo-komodo-mongo" = {
    serviceConfig = {
      Restart = lib.mkOverride 500 "always";
    };
    after = [
      "podman-network-komodo_komodo-network.service"
    ];
    requires = [
      "podman-network-komodo_komodo-network.service"
    ];
    partOf = [
      "podman-compose-komodo-root.target"
    ];
    wantedBy = [
      "podman-compose-komodo-root.target"
    ];
  };
  virtualisation.oci-containers.containers."komodo-komodo-periphery" = {
    image = "ghcr.io/mbecker20/periphery:latest";
    volumes = [
      "/cache/appdata/komodo/komodo-repos:/etc/komodo/repos:rw"
      "/cache/appdata/komodo/komodo-stacks:/etc/komodo/stacks:rw"
      "/var/run/podman/podman.sock:/var/run/docker.sock:rw"
    ];
#    log-driver = "local";
    extraOptions = [
      "--network-alias=komodo-periphery"
      "--network=komodo_komodo-network"
    ];
  };
  systemd.services."podman-komodo-komodo-periphery" = {
    serviceConfig = {
      Restart = lib.mkOverride 500 "no";
    };
    after = [
      "podman-network-komodo_komodo-network.service"
    ];
    requires = [
      "podman-network-komodo_komodo-network.service"
    ];
    partOf = [
      "podman-compose-komodo-root.target"
    ];
    wantedBy = [
      "podman-compose-komodo-root.target"
    ];
  };

  # Networks
  systemd.services."podman-network-komodo_komodo-network" = {
    path = [ pkgs.podman ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "podman network rm -f komodo_komodo-network";
    };
    script = ''
      podman network inspect komodo_komodo-network || podman network create komodo_komodo-network
    '';
    partOf = [ "podman-compose-komodo-root.target" ];
    wantedBy = [ "podman-compose-komodo-root.target" ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."podman-compose-komodo-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = [ "multi-user.target" ];
  };
}
