# Auto-generated using compose2nix v0.2.2.
{ pkgs, lib, ... }:

{
  # Runtime
  virtualisation.podman = {
    enable = true;
    autoPrune.enable = true;
    dockerCompat = true;
    defaultNetwork.settings = {
      # Required for container networking to be able to use names.
      dns_enabled = true;
    };
  };
  virtualisation.oci-containers.backend = "podman";

  # Containers
  virtualisation.oci-containers.containers."it-tools" = {
    image = "corentinth/it-tools:latest";
    ports = [
      "8085:80/tcp"
    ];
    log-driver = "journald";
    extraOptions = [
      "--network-alias=it-tools"
      "--network=it-tools_default"
    ];
  };
  systemd.services."podman-it-tools" = {
    serviceConfig = {
      Restart = lib.mkOverride 500 "always";
    };
    after = [
      "podman-network-it-tools_default.service"
    ];
    requires = [
      "podman-network-it-tools_default.service"
    ];
    partOf = [
      "podman-compose-it-tools-root.target"
    ];
    wantedBy = [
      "podman-compose-it-tools-root.target"
    ];
  };

  # Networks
  systemd.services."podman-network-it-tools_default" = {
    path = [ pkgs.podman ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "podman network rm -f it-tools_default";
    };
    script = ''
      podman network inspect it-tools_default || podman network create it-tools_default
    '';
    partOf = [ "podman-compose-it-tools-root.target" ];
    wantedBy = [ "podman-compose-it-tools-root.target" ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."podman-compose-it-tools-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = [ "multi-user.target" ];
  };
}
